security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /
                always_remember_me: true

    access_control:
    # Admin uniquement
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/category, roles: ROLE_ADMIN }
    - { path: ^/comment, roles: ROLE_ADMIN }

    # Authentifiés (user + admin)
    - { path: ^/articles/new, roles: ROLE_USER }
    - { path: ^/articles/\d+/edit, roles: ROLE_USER }
    - { path: ^/articles/\d+, roles: ROLE_USER }
    - { path: ^/category/new, roles: ROLE_USER }
    - { path: ^/chat, roles: ROLE_USER }
    - { path: ^/profile, roles: ROLE_USER }

    # Public
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/reset-password, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: PUBLIC_ACCESS }
    - { path: ^/api/search, roles: PUBLIC_ACCESS }
    - { path: ^/articles$, roles: PUBLIC_ACCESS }


    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
